@php
$esVentana=$esVentana??false;$rutaConsulta=route($rutaBase.($esVentana?'.ventana':'.index'));$rutaAlterna=route($rutaBase.($esVentana?'.index':'.ventana'),request()->query());$rutaPdf=route($rutaBase.'.pdf',request()->except('page'));
@endphp
<section class="cc-card cc-analytics-root-card">
<header class="cc-card-header cc-card-header-compact"><div><h1 class="cc-title cc-title-compact">{{ $titulo }}</h1><p class="cc-subtitle cc-subtitle-compact">Ciclos completos evaluados por fecha de cierre.</p></div><div class="flex flex-wrap items-center justify-end gap-3">@if($hayConsulta)<a href="{{ $rutaPdf }}" class="cc-btn-secondary cc-btn-wide">Descargar PDF</a>@endif<a href="{{ $rutaAlterna }}" @unless($esVentana) target="_blank" rel="noopener noreferrer" @endunless class="cc-btn-secondary cc-btn-wide">{{ $esVentana?'Volver al sistema':'Abrir en nueva pestaña' }}</a></div></header>
<form method="GET" action="{{ $rutaConsulta }}" class="mb-5"><input type="hidden" name="consultar" value="1"><div class="cc-filter-panel cc-filter-panel-compact cc-filter-panel-inline"><div class="cc-form-section cc-form-section-compact cc-analytics-filter-heading"><div class="cc-form-section-title">Filtros de consulta</div></div><div class="cc-standard-filter-grid cc-analytics-report-filter-grid">
<div class="cc-field"><label for="busqueda">Búsqueda</label><input id="busqueda" name="busqueda" class="cc-input" value="{{ $busqueda }}" maxlength="150" placeholder="Empresa, placa, motorista o ID"></div>
<div class="cc-field"><label>Empresa</label>@if($esDieselCop)<select class="cc-input" name="empresa_ids[]"><option value="">Todas</option>@foreach($empresas as $e)<option value="{{ $e->id }}" @selected(in_array((int)$e->id,$empresaIds,true))>{{ $e->nombre_comercial?:$e->nombre_legal }}</option>@endforeach</select>@else<select class="cc-input" disabled>@foreach($empresas as $e)<option>{{ $e->nombre_comercial?:$e->nombre_legal }}</option>@endforeach</select>@foreach($empresaIds as $id)<input type="hidden" name="empresa_ids[]" value="{{ $id }}">@endforeach @endif</div>
@foreach([['Nombre / Placa','unidad_ids',$unidadesSelector,'placa'],['Motorista','motorista_ids',$motoristasSelector,'nombre_completo']] as [$e,$n,$opts,$attr])<div class="cc-field"><label>{{ $e }}</label><select class="cc-input" name="{{ $n }}[]"><option value="">Todos</option>@foreach($opts as $o)<option value="{{ $o->id }}" @selected(in_array((int)$o->id,$n==='unidad_ids'?$unidadIds:$motoristaIds,true))>{{ $o->{$attr} }}</option>@endforeach</select></div>@endforeach
</div><div class="cc-standard-filter-grid cc-analytics-report-filter-grid cc-analytics-filter-row"><div class="cc-field"><label for="fecha_desde">Fecha desde</label><input id="fecha_desde" name="fecha_desde" type="date" class="cc-input" value="{{ $fechaDesde }}"></div><div class="cc-field"><label for="fecha_hasta">Fecha hasta</label><input id="fecha_hasta" name="fecha_hasta" type="date" class="cc-input" value="{{ $fechaHasta }}"></div><div class="cc-field"><label for="resultado">Resultado</label><select id="resultado" name="resultado" class="cc-input"><option value="">Todos</option>@foreach(['ahorro'=>'Ahorro','sobreconsumo'=>'Sobreconsumo','en_objetivo'=>'En objetivo'] as $v=>$e)<option value="{{ $v }}" @selected($resultado===$v)>{{ $e }}</option>@endforeach</select></div><div class="cc-standard-filter-actions"><button class="cc-btn-primary">Consultar</button><a href="{{ $rutaConsulta }}" class="cc-btn-secondary">Limpiar</a></div></div></div></form>
@if($hayConsulta && $ciclos->isNotEmpty())<div class="cc-summary-grid" data-report-summary><div class="cc-summary-strip cc-summary-grid-row cc-summary-grid-row-four">@foreach([[$ciclosLabel,$resumen['ciclos'],''],[$variableLabel,number_format($resumen['operacion'],2).' '.$variableUnidad,''],['Consumo teórico',number_format($resumen['consumo_teorico'],2).' gal',''],['Consumo real',number_format($resumen['consumo_real'],2).' gal','']] as [$e,$v,$c])<div class="cc-summary-strip-item" data-summary-label="{{ $e }}" data-summary-value="{{ $v }}"><span class="cc-summary-strip-label">{{ $e }}</span><span class="cc-summary-strip-value {{ $c }}">{{ $v }}</span></div>@endforeach</div><div class="cc-summary-strip cc-summary-grid-row cc-summary-grid-row-three">@foreach([['Galones ahorrados',number_format($resumen['ahorro_galones'],2).' gal','cc-summary-strip-value-success'],['Sobreconsumo',number_format($resumen['sobreconsumo_galones'],2).' gal','cc-summary-strip-value-danger'],['Impacto económico neto',($resumen['impacto_neto']<0?'-':'').'$'.number_format(abs($resumen['impacto_neto']),2),$resumen['impacto_neto']>0?'cc-summary-strip-value-success':($resumen['impacto_neto']<0?'cc-summary-strip-value-danger':'')]] as [$e,$v,$c])<div class="cc-summary-strip-item" data-summary-label="{{ $e }}" data-summary-value="{{ $v }}"><span class="cc-summary-strip-label">{{ $e }}</span><span class="cc-summary-strip-value {{ $c }}">{{ $v }}</span></div>@endforeach</div></div>@endif
@if(!$hayConsulta)<div class="cc-empty-panel cc-empty-panel-compact"><h5>Sin resultados</h5><p>No hay resultados para mostrar. Utilice los filtros y presione Consultar.</p></div>@elseif($ciclos->isEmpty())<div class="cc-empty-panel cc-empty-panel-compact"><h5>Sin resultados</h5><p>No hay ciclos completos que coincidan con los filtros seleccionados.</p></div>@else
<div class="cc-result-count">Mostrando <strong>{{ $ciclos->firstItem() }}</strong>-<strong>{{ $ciclos->lastItem() }}</strong> de <strong>{{ $ciclos->total() }}</strong></div><div class="cc-table-adaptive-wrapper"><table class="cc-table-adaptive cc-analytics-table-performance"><thead><tr><th>Empresa</th><th>Nombre / Placa</th><th>Motorista</th><th>Periodo</th><th>{{ $variableLabel }}</th><th>{{ $rendimientoLabel }}</th><th>Consumo</th><th>Diferencia</th><th>Resultado</th><th>Impacto económico</th><th>Acción</th></tr></thead><tbody>
@foreach($ciclos as $c)<tr data-report-cycle-row="{{ $c->id }}"><td>{{ $c->empresa_nombre_snapshot }}</td><td><strong>{{ $c->unidad_placa_snapshot }}</strong></td><td>{{ $c->motorista_nombre_snapshot }}</td><td><span class="cc-table-adaptive-muted">Inicio</span> {{ $c->abastecimientoAnterior->fecha_hora_abastecimiento->format('d/m/Y H:i') }}<br><span class="cc-table-adaptive-muted">Cierre</span> {{ $c->fecha_hora_abastecimiento->format('d/m/Y H:i') }}</td><td class="text-right">{{ number_format((float)$c->{$campoVariable},2) }} {{ $variableUnidad }}</td>
<td class="text-right">@if($rendimientoEsperadoCampo)<span class="cc-table-adaptive-muted">Esperado</span> {{ number_format((float)$c->{$rendimientoEsperadoCampo},2) }}<br><span class="cc-table-adaptive-muted">Real</span> {{ number_format((float)$c->{$rendimientoRealCampo},2) }} {{ $rendimientoUnidad }}@else<span class="cc-table-adaptive-muted">Esperado</span> {{ $c->total_viajes>0?number_format((float)$c->consumo_teorico_ciclo/$c->total_viajes,2):'0.00' }}<br><span class="cc-table-adaptive-muted">Real</span> {{ $c->total_viajes>0?number_format((float)$c->consumo_real_ciclo/$c->total_viajes,2):'0.00' }} {{ $rendimientoUnidad }}@endif</td>
<td class="text-right"><span class="cc-table-adaptive-muted">Teórico</span> {{ number_format((float)$c->consumo_teorico_ciclo,2) }}<br><span class="cc-table-adaptive-muted">Real</span> {{ number_format((float)$c->consumo_real_ciclo,2) }} gal</td><td class="text-right">{{ number_format($c->diferencia_absoluta_reporte,2) }} gal</td><td><span @class(['cc-badge','cc-badge-active'=>$c->resultado_reporte==='Ahorro','cc-badge-danger'=>$c->resultado_reporte==='Sobreconsumo','cc-badge-info'=>$c->resultado_reporte==='En objetivo'])>{{ $c->resultado_reporte }}</span></td><td class="text-right"><strong @class(['text-[var(--cc-success)]'=>$c->resultado_reporte==='Ahorro','text-[var(--cc-danger)]'=>$c->resultado_reporte==='Sobreconsumo'])>{{ $c->resultado_reporte==='Sobreconsumo'?'-':($c->resultado_reporte==='Ahorro'?'+':'') }}${{ number_format($c->impacto_economico_reporte,2) }}</strong></td><td><a href="{{ route($rutaBase.'.show',array_merge(['ciclo'=>$c->id],request()->query())) }}" class="cc-btn-secondary">Ver detalle</a></td></tr>@endforeach
</tbody></table></div><div class="mt-6">{{ $ciclos->links() }}</div>@endif</section>
