@php
$esVentana=$esVentana??false;$base='reportes.gestion-combustible-motorista';$rutaConsulta=route($base.($esVentana?'.ventana':'.index'));$rutaAlterna=route($base.($esVentana?'.index':'.ventana'),request()->query());$rutaPdf=route($base.'.pdf',request()->except('page'));
$dinero=fn($v)=>(float)$v>0?'+$'.number_format((float)$v,2):((float)$v<0?'-$'.number_format(abs((float)$v),2):'$0.00');
@endphp
<section class="cc-card cc-analytics-root-card">
<header class="cc-card-header cc-card-header-compact"><div><h1 class="cc-title cc-title-compact">Gestión de Combustible por Motorista</h1><p class="cc-subtitle cc-subtitle-compact">Evidencia histórica consolidada por motorista y fecha de cierre del ciclo.</p></div><div class="flex flex-wrap gap-3">@if($hayConsulta)<a href="{{ $rutaPdf }}" class="cc-btn-secondary">Descargar PDF</a>@endif<a href="{{ $rutaAlterna }}" @unless($esVentana) target="_blank" rel="noopener" @endunless class="cc-btn-secondary">{{ $esVentana?'Volver al sistema':'Abrir en nueva pestaña' }}</a></div></header>
<form method="GET" action="{{ $rutaConsulta }}" class="mb-5"><input type="hidden" name="consultar" value="1"><div class="cc-filter-panel cc-filter-panel-compact cc-filter-panel-inline"><div class="cc-form-section cc-form-section-compact cc-analytics-filter-heading"><div class="cc-form-section-title">Filtros de consulta</div></div><div class="cc-standard-filter-grid cc-analytics-report-filter-grid">
@php $multiples=[['Empresa','empresa_ids',$empresas,$empresaIds,fn($e)=>$e->nombre_comercial?:$e->nombre_legal],['Motorista','motorista_ids',$motoristasSelector,$motoristaIds,fn($m)=>$m->nombre_completo],['Unidad','unidad_ids',$unidadesSelector,$unidadIds,fn($u)=>$u->placa],['Modelo de medición','modelo_medicion',collect($modelos)->map(fn($label,$id)=>(object)compact('id','label')),$modelosSeleccionados,fn($m)=>$m->label]]; @endphp
@foreach($multiples as [$titulo,$nombre,$opciones,$seleccionados,$etiqueta])<div class="cc-field"><label>{{ $titulo }}</label>@if($nombre==='empresa_ids'&&!$esDieselCop)<div class="cc-filter-multiselect"><button type="button" disabled class="cc-filter-multiselect-toggle"><span>{{ $etiqueta($opciones->first()) }}</span></button></div>@foreach($empresaIds as $id)<input type="hidden" name="empresa_ids[]" value="{{ $id }}">@endforeach @else<div class="cc-filter-multiselect cc-filter-multiselect-readable" data-cc-filter-multiselect data-all-text="Todos"><button type="button" class="cc-filter-multiselect-toggle" data-cc-filter-toggle><span data-cc-filter-label>{{ $seleccionados===[]?'Todos':count($seleccionados).' seleccionados' }}</span><span class="cc-filter-multiselect-arrow">⌄</span></button><div class="cc-filter-multiselect-menu" data-cc-filter-menu><div class="cc-filter-multiselect-list"><label class="cc-filter-multiselect-option cc-filter-multiselect-option-master"><input type="checkbox" data-cc-filter-check-all><span>Seleccionar todo</span></label>@foreach($opciones as $opcion)<label class="cc-filter-multiselect-option" data-cc-filter-option><input type="checkbox" name="{{ $nombre }}[]" value="{{ $opcion->id }}" @checked(in_array(is_numeric($opcion->id)?(int)$opcion->id:$opcion->id,$seleccionados,true)) data-cc-filter-checkbox><span data-cc-filter-option-label>{{ $etiqueta($opcion) }}</span></label>@endforeach</div></div></div>@endif</div>@endforeach
<div class="cc-field"><label for="fecha_desde">Fecha desde</label><input id="fecha_desde" name="fecha_desde" type="date" class="cc-input" value="{{ $fechaDesde }}"></div><div class="cc-field"><label for="fecha_hasta">Fecha hasta</label><input id="fecha_hasta" name="fecha_hasta" type="date" class="cc-input" value="{{ $fechaHasta }}"></div>
<div class="cc-field"><label>Resultado</label><div class="cc-filter-multiselect cc-filter-multiselect-compact" data-cc-filter-radio><button type="button" class="cc-filter-multiselect-toggle" data-cc-filter-toggle><span data-cc-filter-label>{{ ['ahorro'=>'Ahorro','sobreconsumo'=>'Sobreconsumo','en_objetivo'=>'En objetivo'][$resultado]??'Todos' }}</span><span class="cc-filter-multiselect-arrow">⌄</span></button><div class="cc-filter-multiselect-menu" data-cc-filter-menu><div class="cc-filter-multiselect-list">@foreach([''=>'Todos','ahorro'=>'Ahorro','sobreconsumo'=>'Sobreconsumo','en_objetivo'=>'En objetivo'] as $v=>$e)<label class="cc-filter-multiselect-option" data-cc-filter-option><input type="radio" name="resultado" value="{{ $v }}" @checked($resultado===$v)><span data-cc-filter-option-label>{{ $e }}</span></label>@endforeach</div></div></div></div><div class="cc-standard-filter-actions"><button class="cc-btn-primary">Consultar</button><a href="{{ $rutaConsulta }}" class="cc-btn-secondary">Limpiar</a></div></div></div></form>
@if($hayConsulta&&$motoristas->isNotEmpty())
@php $kpis1=[['Motoristas evaluados',(int)$resumen['motoristas'],''],['Ciclos completos',(int)$resumen['ciclos'],''],['Unidades manejadas',(int)$resumen['unidades'],''],['Kilómetros recorridos',number_format($resumen['kilometros'],2).' km',''],['Galones consumidos',number_format($resumen['consumo_real'],2).' gal',''],['Costo promedio por galón',$resumen['costo_promedio']===null?'—':'$'.number_format($resumen['costo_promedio'],2).'/gal','']];$kpis2=[['Consumo teórico',number_format($resumen['consumo_teorico'],2).' gal',''],['Galones ahorrados',number_format($resumen['galones_ahorrados'],2).' gal','cc-summary-strip-value-success'],['Sobreconsumo',number_format($resumen['sobreconsumo'],2).' gal','cc-summary-strip-value-danger'],['Ahorro económico','$'.number_format($resumen['ahorro_economico'],2),'cc-summary-strip-value-success'],['Costo de sobreconsumo','$'.number_format($resumen['costo_sobreconsumo'],2),'cc-summary-strip-value-danger'],['Impacto económico neto',$dinero($resumen['impacto_neto']),$resumen['impacto_neto']>0?'cc-summary-strip-value-success':($resumen['impacto_neto']<0?'cc-summary-strip-value-danger':'')]]; @endphp
<div class="cc-summary-grid" data-report-summary>@foreach([$kpis1,$kpis2] as $fila)<div class="cc-summary-strip cc-summary-grid-row cc-summary-grid-row-six">@foreach($fila as [$e,$v,$c])<div class="cc-summary-strip-item" data-summary-label="{{ $e }}" data-summary-value="{{ $v }}"><span class="cc-summary-strip-label">{{ $e }}</span><span class="cc-summary-strip-value {{ $c }}">{{ $v }}</span></div>@endforeach</div>@endforeach</div>
@endif
@if(!$hayConsulta)<div class="cc-empty-panel cc-empty-panel-compact"><h5>Sin resultados</h5><p>No hay resultados para mostrar. Utilice los filtros y presione Consultar.</p></div>@elseif($motoristas->isEmpty())<div class="cc-empty-panel cc-empty-panel-compact"><h5>Sin resultados</h5><p>No hay ciclos completos que coincidan con los filtros seleccionados.</p></div>@else
<div class="cc-result-count">Mostrando <strong class="cc-result-count-value">{{ $motoristas->firstItem() }}</strong><span aria-hidden="true">–</span><strong class="cc-result-count-value">{{ $motoristas->lastItem() }}</strong><span>de</span><strong class="cc-result-count-value">{{ $motoristas->total() }}</strong></div><div class="cc-table-adaptive-wrapper cc-analytics-performance-table-wrapper"><table class="cc-table-adaptive cc-analytics-table-driver-management"><thead><tr><th>Motorista</th><th>Ciclos</th><th>Unidades</th><th>Km recorridos</th><th>Galones consumidos</th><th>Galones ahorrados</th><th>Sobreconsumo</th><th>% favorables</th><th>Impacto neto</th><th>Resultado</th><th>Acción</th></tr></thead><tbody>
@foreach($motoristas as $m)@php $neto=(float)$m->impacto_neto;$resultadoNeto=$neto>0?'Ahorro':($neto<0?'Sobreconsumo':'En objetivo'); @endphp<tr data-report-driver-row="{{ $m->motorista_id }}"><td class="whitespace-nowrap"><strong class="cc-table-adaptive-strong">{{ $m->motorista_nombre }}</strong></td><td class="text-right">{{ $m->ciclos }}</td><td class="text-right">{{ $m->unidades }}</td><td class="text-right whitespace-nowrap">{{ number_format($m->kilometros,2) }} km</td><td class="text-right whitespace-nowrap">{{ number_format($m->consumo_real,2) }} gal</td><td class="text-right whitespace-nowrap">{{ number_format($m->galones_ahorrados,2) }} gal</td><td class="text-right whitespace-nowrap">{{ number_format($m->sobreconsumo,2) }} gal</td><td class="text-right whitespace-nowrap">{{ number_format($m->porcentaje_favorable,1) }}%</td><td class="text-right whitespace-nowrap"><strong @class(['text-[var(--cc-success)]'=>$neto>0,'text-[var(--cc-danger)]'=>$neto<0])>{{ $dinero($neto) }}</strong></td><td><span @class(['cc-badge','cc-badge-active'=>$neto>0,'cc-badge-danger'=>$neto<0,'cc-badge-info'=>$neto==0])>{{ $resultadoNeto }}</span></td><td><a class="cc-btn-secondary whitespace-nowrap" href="{{ route($base.'.show',array_merge(['motorista'=>$m->motorista_id],request()->query())) }}">Ver detalle</a></td></tr>@endforeach
</tbody></table></div><div class="mt-6">{{ $motoristas->links() }}</div>@endif</section>
@include('reportes.partials.filter-radio-script')
