<!DOCTYPE html><html lang="es"><head><meta charset="utf-8"><title>Gestión de combustible · {{ $motorista->nombre_completo }}</title><style>
@page{margin:15mm 7mm 14mm}body{font-family:DejaVu Sans,sans-serif;color:#25343b;font-size:7px}.wide,.summary,.report{width:100%;border-collapse:collapse}.header{border-bottom:2px solid #147d82;margin-bottom:8px;padding-bottom:6px}.logo{width:120px}.title{text-align:right;color:#114d57;font-size:14px;font-weight:bold}.subtitle{text-align:right;color:#68797e}.section{margin-top:9px}.section-title{background:#126d73;color:#fff;font-size:9px;font-weight:bold;padding:4px 6px}.summary td{border:1px solid #d3dfe1;padding:5px;text-align:center}.value{font-size:8px;font-weight:bold;color:#114d57}.label{font-size:5.8px;color:#68797e;text-transform:uppercase}.report thead{display:table-header-group}.report tr{page-break-inside:avoid}.report th{background:#e8f1f2;color:#114d57;padding:4px 2px}.report td{border:1px solid #d3dfe1;padding:3px 2px}.right{text-align:right}.success{color:#147048}.danger{color:#9e3f34}.footer{border-top:1px solid #cddbdd;bottom:-9mm;position:fixed;width:100%;color:#77878c;font-size:6px}
</style></head><body>@php
$dinero=fn($v)=>(float)$v>0?'+$'.number_format((float)$v,2):((float)$v<0?'-$'.number_format(abs((float)$v),2):'$0.00');
$actividad=fn($c)=>match($c->modelo_medicion){App\Models\Abastecimiento::MODELO_GALONES_HORA=>number_format((float)$c->diferencia_horometro,2).' h',App\Models\Abastecimiento::MODELO_GALONES_VIAJE=>number_format((int)$c->total_viajes).' viajes',default=>number_format((float)$c->diferencia_kilometraje,2).' km'};
@endphp
<div class="header"><table class="wide"><tr><td><img class="logo" src="{{ $logoPath }}"></td><td><div class="title">Gestión de combustible · {{ $motorista->nombre_completo }}</div><div class="subtitle">{{ $empresasHistoricas->implode(' · ') }} · Período evaluado: {{ $periodoEvaluado }}<br>Generado: {{ $generadoEn->format('d/m/Y H:i') }}</div></td></tr></table></div>
@php $kpis=[['Ciclos completos',$resumen['ciclos']],['Unidades manejadas',$resumen['unidades']],['Km recorridos',number_format($resumen['kilometros'],2).' km'],['Galones consumidos',number_format($resumen['consumo_real'],2).' gal'],['Costo promedio por galón',$resumen['costo_promedio']===null?'—':'$'.number_format($resumen['costo_promedio'],2).'/gal'],['Consumo teórico',number_format($resumen['consumo_teorico'],2).' gal'],['Galones ahorrados',number_format($resumen['galones_ahorrados'],2).' gal'],['Sobreconsumo',number_format($resumen['sobreconsumo'],2).' gal'],['Ahorro económico','$'.number_format($resumen['ahorro_economico'],2)],['Costo de sobreconsumo','$'.number_format($resumen['costo_sobreconsumo'],2)],['Impacto económico neto',$dinero($resumen['impacto_neto'])],['Ciclos con ahorro',$resumen['ciclos_ahorro']],['Ciclos con sobreconsumo',$resumen['ciclos_sobreconsumo']],['Ciclos en objetivo',$resumen['ciclos_objetivo']],['% ciclos favorables',number_format($resumen['porcentaje_favorable'],1).'%'],['Impacto neto por 1,000 km',$impactoMilKm===null?'—':$dinero($impactoMilKm).' / 1,000 km']]; @endphp
<table class="summary">@foreach(array_chunk($kpis,4) as $fila)<tr>@foreach($fila as [$e,$v])<td><div class="value">{{ $v }}</div><div class="label">{{ $e }}</div></td>@endforeach @for($i=count($fila);$i<4;$i++)<td></td>@endfor</tr>@endforeach</table>
<div class="section"><div class="section-title">Desglose por modelo de medición</div><table class="report"><thead><tr><th>Modelo</th><th>Ciclos</th><th>Actividad</th><th>Consumo teórico</th><th>Consumo real</th><th>Diferencia</th><th>Rendimiento teórico ponderado</th><th>Rendimiento real ponderado</th><th>Impacto económico</th></tr></thead><tbody>@foreach($desglose as $d)@php $esKm=$d->modelo_medicion===App\Models\Abastecimiento::MODELO_KILOMETROS_GALON;$unidad=$esKm?'km':($d->modelo_medicion===App\Models\Abastecimiento::MODELO_GALONES_HORA?'h':'viajes');$unidadR=$esKm?'km/gal':($d->modelo_medicion===App\Models\Abastecimiento::MODELO_GALONES_HORA?'gal/h':'gal/viaje');$teorico=$esKm?($d->consumo_teorico>0?$d->actividad/$d->consumo_teorico:null):($d->actividad>0?$d->consumo_teorico/$d->actividad:null);$real=$esKm?($d->consumo_real>0?$d->actividad/$d->consumo_real:null):($d->actividad>0?$d->consumo_real/$d->actividad:null); @endphp<tr data-pdf-model="{{ $d->modelo_medicion }}"><td>{{ $modelos[$d->modelo_medicion] }}</td><td>{{ $d->ciclos }}</td><td class="right">{{ $unidad==='viajes'?number_format($d->actividad,0):number_format($d->actividad,2) }} {{ $unidad }}</td><td class="right">{{ number_format($d->consumo_teorico,2) }} gal</td><td class="right">{{ number_format($d->consumo_real,2) }} gal</td><td class="right">{{ number_format(abs($d->consumo_teorico-$d->consumo_real),2) }} gal</td><td class="right">{{ $teorico===null?'—':number_format($teorico,2).' '.$unidadR }}</td><td class="right">{{ $real===null?'—':number_format($real,2).' '.$unidadR }}</td><td class="right {{ $d->impacto_neto>0?'success':($d->impacto_neto<0?'danger':'') }}">{{ $dinero($d->impacto_neto) }}</td></tr>@endforeach</tbody></table></div>
<div class="section"><div class="section-title">Historial de ciclos</div><table class="report"><thead><tr><th>Fecha de cierre</th><th>Unidad</th><th>Modelo</th><th>Actividad</th><th>Consumo teórico</th><th>Consumo real</th><th>Diferencia</th><th>Resultado</th><th>Impacto económico</th></tr></thead><tbody>@foreach($ciclos as $c)<tr data-pdf-driver-cycle="{{ $c->id }}"><td>{{ $c->fecha_hora_abastecimiento->format('d/m/Y H:i') }}</td><td>{{ $c->unidad_placa_snapshot }}</td><td>{{ $modelos[$c->modelo_medicion] }}</td><td class="right">{{ $actividad($c) }}</td><td class="right">{{ number_format($c->consumo_teorico_ciclo,2) }} gal</td><td class="right">{{ number_format($c->consumo_real_ciclo,2) }} gal</td><td class="right">{{ number_format($c->diferencia_absoluta_reporte,2) }} gal</td><td class="{{ $c->resultado_reporte==='Ahorro'?'success':($c->resultado_reporte==='Sobreconsumo'?'danger':'') }}">{{ $c->resultado_reporte }}</td><td class="right {{ $c->resultado_reporte==='Ahorro'?'success':($c->resultado_reporte==='Sobreconsumo'?'danger':'') }}">{{ $c->resultado_reporte==='Ahorro'?'+':($c->resultado_reporte==='Sobreconsumo'?'-':'') }}${{ number_format($c->impacto_economico_reporte,2) }}</td></tr>@endforeach</tbody></table></div>
<div class="footer">CC-Flota · Gestión de combustible · {{ $motorista->nombre_completo }} · {{ $ciclos->count() }} ciclo(s)</div></body></html>
