<?php

namespace App\Support;

use InvalidArgumentException;

class PlantillasPuntosSeguridad
{
    public static function porPlantilla(string $plantilla): array
    {
        return match ($plantilla) {
            'plantilla_1_tanque' => self::PLANTILLA_1_TANQUE(),
            'plantilla_2_tanques' => self::PLANTILLA_2_TANQUES(),
            'plantilla_3_tanques' => self::PLANTILLA_3_TANQUES(),
            default => throw new InvalidArgumentException("Plantilla de puntos de seguridad no válida: {$plantilla}"),
        };
    }

    public static function cantidadEsperada(string $plantilla): int
    {
        return count(self::porPlantilla($plantilla));
    }

    private static function PLANTILLA_1_TANQUE(): array
    {
        return [
                ['orden' => 1, 'codigo_punto' => 'ALIM-01', 'grupo' => 'Alimentación', 'subgrupo' => 'Depósito', 'nombre_punto' => 'Alimentación depósito único', 'posicion_tanque' => 'Único', 'tipo_punto' => 'depósito', 'requiere_marchamo' => true, 'criterio_origen' => 'Derivado: reemplaza izquierdo/derecho por depósito único'],
                ['orden' => 2, 'codigo_punto' => 'ALIM-02', 'grupo' => 'Alimentación', 'subgrupo' => 'Depósito', 'nombre_punto' => 'Distribuidor alimentación depósito único', 'posicion_tanque' => 'Único', 'tipo_punto' => 'distribuidor', 'requiere_marchamo' => true, 'criterio_origen' => 'Derivado: reemplaza izquierdo/derecho por depósito único'],
                ['orden' => 3, 'codigo_punto' => 'ALIM-06', 'grupo' => 'Alimentación', 'subgrupo' => 'Filtro primario', 'nombre_punto' => 'Entrada filtro combustible primario', 'posicion_tanque' => 'Común', 'tipo_punto' => 'línea', 'requiere_marchamo' => true, 'criterio_origen' => 'Punto común derivado del estándar documentado'],
                ['orden' => 4, 'codigo_punto' => 'ALIM-07', 'grupo' => 'Alimentación', 'subgrupo' => 'Filtro primario', 'nombre_punto' => 'Dreno filtro combustible primario', 'posicion_tanque' => 'Común', 'tipo_punto' => 'filtro', 'requiere_marchamo' => true, 'criterio_origen' => 'Punto común derivado del estándar documentado'],
                ['orden' => 5, 'codigo_punto' => 'ALIM-08', 'grupo' => 'Alimentación', 'subgrupo' => 'Filtro primario', 'nombre_punto' => 'Salida filtro combustible primario', 'posicion_tanque' => 'Común', 'tipo_punto' => 'línea', 'requiere_marchamo' => true, 'criterio_origen' => 'Corrección ortográfica sugerida: Filtro'],
                ['orden' => 6, 'codigo_punto' => 'ALIM-09', 'grupo' => 'Alimentación', 'subgrupo' => 'Filtro secundario', 'nombre_punto' => 'Alimentador filtro combustible secundario', 'posicion_tanque' => 'Común', 'tipo_punto' => 'línea', 'requiere_marchamo' => true, 'criterio_origen' => 'Punto común derivado del estándar documentado'],
                ['orden' => 7, 'codigo_punto' => 'ALIM-10', 'grupo' => 'Alimentación', 'subgrupo' => 'Filtro secundario', 'nombre_punto' => 'Entrada filtro combustible secundario', 'posicion_tanque' => 'Común', 'tipo_punto' => 'línea', 'requiere_marchamo' => true, 'criterio_origen' => 'Punto común derivado del estándar documentado'],
                ['orden' => 8, 'codigo_punto' => 'ALIM-11', 'grupo' => 'Alimentación', 'subgrupo' => 'Filtro secundario', 'nombre_punto' => 'Salida filtro combustible secundario', 'posicion_tanque' => 'Común', 'tipo_punto' => 'línea', 'requiere_marchamo' => true, 'criterio_origen' => 'Corrección ortográfica sugerida: Filtro'],
                ['orden' => 9, 'codigo_punto' => 'ALIM-12', 'grupo' => 'Alimentación', 'subgrupo' => 'Transferencia', 'nombre_punto' => 'Entrada transferencia', 'posicion_tanque' => 'Común', 'tipo_punto' => 'transferencia', 'requiere_marchamo' => true, 'criterio_origen' => 'Punto común derivado del estándar documentado'],
                ['orden' => 10, 'codigo_punto' => 'ALIM-13', 'grupo' => 'Alimentación', 'subgrupo' => 'Transferencia', 'nombre_punto' => 'Salida transferencia', 'posicion_tanque' => 'Común', 'tipo_punto' => 'transferencia', 'requiere_marchamo' => true, 'criterio_origen' => 'Punto común derivado del estándar documentado'],
                ['orden' => 11, 'codigo_punto' => 'ALIM-14', 'grupo' => 'Alimentación', 'subgrupo' => 'Motor', 'nombre_punto' => 'Unión alimentación motor', 'posicion_tanque' => 'Común', 'tipo_punto' => 'unión', 'requiere_marchamo' => true, 'criterio_origen' => 'Punto común derivado del estándar documentado'],
                ['orden' => 12, 'codigo_punto' => 'ALIM-15', 'grupo' => 'Alimentación', 'subgrupo' => 'Motor', 'nombre_punto' => 'Entrada motor', 'posicion_tanque' => 'Común', 'tipo_punto' => 'motor', 'requiere_marchamo' => true, 'criterio_origen' => 'Punto común derivado del estándar documentado'],
                ['orden' => 13, 'codigo_punto' => 'RET-16', 'grupo' => 'Retorno', 'subgrupo' => 'Motor', 'nombre_punto' => 'Retorno motor', 'posicion_tanque' => 'Común', 'tipo_punto' => 'motor', 'requiere_marchamo' => true, 'criterio_origen' => 'Punto común derivado del estándar documentado'],
                ['orden' => 14, 'codigo_punto' => 'RET-17', 'grupo' => 'Retorno', 'subgrupo' => 'Motor', 'nombre_punto' => 'Unión retorno motor', 'posicion_tanque' => 'Común', 'tipo_punto' => 'unión', 'requiere_marchamo' => true, 'criterio_origen' => 'Punto común derivado del estándar documentado'],
                ['orden' => 15, 'codigo_punto' => 'RET-18', 'grupo' => 'Retorno', 'subgrupo' => 'Depósito', 'nombre_punto' => 'Distribuidor retorno depósito único', 'posicion_tanque' => 'Único', 'tipo_punto' => 'distribuidor', 'requiere_marchamo' => true, 'criterio_origen' => 'Derivado: reemplaza izquierdo/derecho por depósito único'],
                ['orden' => 16, 'codigo_punto' => 'RET-19', 'grupo' => 'Retorno', 'subgrupo' => 'Depósito', 'nombre_punto' => 'Entrada retorno depósito único', 'posicion_tanque' => 'Único', 'tipo_punto' => 'retorno', 'requiere_marchamo' => true, 'criterio_origen' => 'Derivado: reemplaza izquierdo/derecho por depósito único'],
                ['orden' => 17, 'codigo_punto' => 'OTR-20', 'grupo' => 'Otros', 'subgrupo' => 'Depósito', 'nombre_punto' => 'Tapón depósito único', 'posicion_tanque' => 'Único', 'tipo_punto' => 'tapón', 'requiere_marchamo' => true, 'criterio_origen' => 'Derivado: reemplaza izquierdo/derecho por depósito único'],
                ['orden' => 18, 'codigo_punto' => 'OTR-21', 'grupo' => 'Otros', 'subgrupo' => 'Depósito', 'nombre_punto' => 'Respiradero depósito único', 'posicion_tanque' => 'Único', 'tipo_punto' => 'respiradero', 'requiere_marchamo' => true, 'criterio_origen' => 'Derivado: reemplaza izquierdo/derecho por depósito único'],
                ['orden' => 19, 'codigo_punto' => 'OTR-22', 'grupo' => 'Otros', 'subgrupo' => 'Depósito', 'nombre_punto' => 'Medidor depósito único', 'posicion_tanque' => 'Único', 'tipo_punto' => 'medidor', 'requiere_marchamo' => true, 'criterio_origen' => 'Derivado: reemplaza izquierdo/derecho por depósito único'],
                ['orden' => 20, 'codigo_punto' => 'OTR-23', 'grupo' => 'Otros', 'subgrupo' => 'Depósito', 'nombre_punto' => 'Dreno depósito único', 'posicion_tanque' => 'Único', 'tipo_punto' => 'dreno', 'requiere_marchamo' => true, 'criterio_origen' => 'Derivado: reemplaza izquierdo/derecho por depósito único'],
                ['orden' => 21, 'codigo_punto' => 'OTR-30', 'grupo' => 'Otros', 'subgrupo' => 'Filtro', 'nombre_punto' => 'Filtro combustible primario', 'posicion_tanque' => 'Común', 'tipo_punto' => 'filtro', 'requiere_marchamo' => true, 'criterio_origen' => 'Punto común derivado del estándar documentado'],
                ['orden' => 22, 'codigo_punto' => 'OTR-31', 'grupo' => 'Otros', 'subgrupo' => 'Filtro', 'nombre_punto' => 'Filtro combustible secundario', 'posicion_tanque' => 'Común', 'tipo_punto' => 'filtro', 'requiere_marchamo' => true, 'criterio_origen' => 'Punto común derivado del estándar documentado'],
                ['orden' => 23, 'codigo_punto' => 'OTR-32', 'grupo' => 'Otros', 'subgrupo' => 'Sensor', 'nombre_punto' => 'Sensor filtro combustible A', 'posicion_tanque' => 'Común', 'tipo_punto' => 'sensor', 'requiere_marchamo' => true, 'criterio_origen' => 'Punto común derivado del estándar documentado'],
                ['orden' => 24, 'codigo_punto' => 'OTR-33', 'grupo' => 'Otros', 'subgrupo' => 'Sensor', 'nombre_punto' => 'Sensor filtro combustible B', 'posicion_tanque' => 'Común', 'tipo_punto' => 'sensor', 'requiere_marchamo' => true, 'criterio_origen' => 'Punto común derivado del estándar documentado'],
                ['orden' => 25, 'codigo_punto' => 'OTR-34', 'grupo' => 'Otros', 'subgrupo' => 'Módulo', 'nombre_punto' => 'Base módulo entrada', 'posicion_tanque' => 'Común', 'tipo_punto' => 'módulo', 'requiere_marchamo' => true, 'criterio_origen' => 'Punto común derivado del estándar documentado'],
                ['orden' => 26, 'codigo_punto' => 'OTR-35', 'grupo' => 'Otros', 'subgrupo' => 'Módulo', 'nombre_punto' => 'Base módulo salida', 'posicion_tanque' => 'Común', 'tipo_punto' => 'módulo', 'requiere_marchamo' => true, 'criterio_origen' => 'Punto común derivado del estándar documentado'],
                ['orden' => 27, 'codigo_punto' => 'OTR-36', 'grupo' => 'Otros', 'subgrupo' => 'Transferencia', 'nombre_punto' => 'Desairador transferencia', 'posicion_tanque' => 'Común', 'tipo_punto' => 'transferencia', 'requiere_marchamo' => true, 'criterio_origen' => 'Punto común derivado del estándar documentado'],
                ['orden' => 28, 'codigo_punto' => 'OTR-37', 'grupo' => 'Otros', 'subgrupo' => 'Sensor', 'nombre_punto' => 'Sensor presión transferencia', 'posicion_tanque' => 'Común', 'tipo_punto' => 'sensor', 'requiere_marchamo' => true, 'criterio_origen' => 'Punto común derivado del estándar documentado'],
                ['orden' => 29, 'codigo_punto' => 'OTR-38', 'grupo' => 'Otros', 'subgrupo' => 'Transferencia', 'nombre_punto' => 'Tapón desairador transferencia', 'posicion_tanque' => 'Común', 'tipo_punto' => 'tapón', 'requiere_marchamo' => true, 'criterio_origen' => 'Punto común derivado del estándar documentado'],
        ];
    }

    private static function PLANTILLA_2_TANQUES(): array
    {
        return [
                ['orden' => 1, 'codigo_punto' => 'ALIM-01', 'grupo' => 'Alimentación', 'subgrupo' => 'Depósito', 'nombre_punto' => 'Alimentación depósito izquierdo', 'posicion_tanque' => 'Izquierdo', 'tipo_punto' => 'depósito', 'requiere_marchamo' => true, 'criterio_origen' => 'Documentado en listado estándar'],
                ['orden' => 2, 'codigo_punto' => 'ALIM-02', 'grupo' => 'Alimentación', 'subgrupo' => 'Depósito', 'nombre_punto' => 'Distribuidor alimentación depósito izquierdo', 'posicion_tanque' => 'Izquierdo', 'tipo_punto' => 'distribuidor', 'requiere_marchamo' => true, 'criterio_origen' => 'Documentado en listado estándar'],
                ['orden' => 3, 'codigo_punto' => 'ALIM-03', 'grupo' => 'Alimentación', 'subgrupo' => 'Depósito', 'nombre_punto' => 'Alimentación depósito derecho', 'posicion_tanque' => 'Derecho', 'tipo_punto' => 'depósito', 'requiere_marchamo' => true, 'criterio_origen' => 'Documentado en listado estándar'],
                ['orden' => 4, 'codigo_punto' => 'ALIM-04', 'grupo' => 'Alimentación', 'subgrupo' => 'Depósito', 'nombre_punto' => 'Distribuidor alimentación depósito derecho', 'posicion_tanque' => 'Derecho', 'tipo_punto' => 'distribuidor', 'requiere_marchamo' => true, 'criterio_origen' => 'Documentado en listado estándar'],
                ['orden' => 5, 'codigo_punto' => 'ALIM-05', 'grupo' => 'Alimentación', 'subgrupo' => 'Unión entre depósitos', 'nombre_punto' => 'Unión alimentación izquierdo-derecho', 'posicion_tanque' => 'Izquierdo-Derecho', 'tipo_punto' => 'unión', 'requiere_marchamo' => true, 'criterio_origen' => 'Documentado como UNION ALIMENTACION IZQ-DER'],
                ['orden' => 6, 'codigo_punto' => 'ALIM-06', 'grupo' => 'Alimentación', 'subgrupo' => 'Filtro primario', 'nombre_punto' => 'Entrada filtro combustible primario', 'posicion_tanque' => 'Común', 'tipo_punto' => 'línea', 'requiere_marchamo' => true, 'criterio_origen' => 'Punto común derivado del estándar documentado'],
                ['orden' => 7, 'codigo_punto' => 'ALIM-07', 'grupo' => 'Alimentación', 'subgrupo' => 'Filtro primario', 'nombre_punto' => 'Dreno filtro combustible primario', 'posicion_tanque' => 'Común', 'tipo_punto' => 'filtro', 'requiere_marchamo' => true, 'criterio_origen' => 'Punto común derivado del estándar documentado'],
                ['orden' => 8, 'codigo_punto' => 'ALIM-08', 'grupo' => 'Alimentación', 'subgrupo' => 'Filtro primario', 'nombre_punto' => 'Salida filtro combustible primario', 'posicion_tanque' => 'Común', 'tipo_punto' => 'línea', 'requiere_marchamo' => true, 'criterio_origen' => 'Corrección ortográfica sugerida: Filtro'],
                ['orden' => 9, 'codigo_punto' => 'ALIM-09', 'grupo' => 'Alimentación', 'subgrupo' => 'Filtro secundario', 'nombre_punto' => 'Alimentador filtro combustible secundario', 'posicion_tanque' => 'Común', 'tipo_punto' => 'línea', 'requiere_marchamo' => true, 'criterio_origen' => 'Punto común derivado del estándar documentado'],
                ['orden' => 10, 'codigo_punto' => 'ALIM-10', 'grupo' => 'Alimentación', 'subgrupo' => 'Filtro secundario', 'nombre_punto' => 'Entrada filtro combustible secundario', 'posicion_tanque' => 'Común', 'tipo_punto' => 'línea', 'requiere_marchamo' => true, 'criterio_origen' => 'Punto común derivado del estándar documentado'],
                ['orden' => 11, 'codigo_punto' => 'ALIM-11', 'grupo' => 'Alimentación', 'subgrupo' => 'Filtro secundario', 'nombre_punto' => 'Salida filtro combustible secundario', 'posicion_tanque' => 'Común', 'tipo_punto' => 'línea', 'requiere_marchamo' => true, 'criterio_origen' => 'Corrección ortográfica sugerida: Filtro'],
                ['orden' => 12, 'codigo_punto' => 'ALIM-12', 'grupo' => 'Alimentación', 'subgrupo' => 'Transferencia', 'nombre_punto' => 'Entrada transferencia', 'posicion_tanque' => 'Común', 'tipo_punto' => 'transferencia', 'requiere_marchamo' => true, 'criterio_origen' => 'Punto común derivado del estándar documentado'],
                ['orden' => 13, 'codigo_punto' => 'ALIM-13', 'grupo' => 'Alimentación', 'subgrupo' => 'Transferencia', 'nombre_punto' => 'Salida transferencia', 'posicion_tanque' => 'Común', 'tipo_punto' => 'transferencia', 'requiere_marchamo' => true, 'criterio_origen' => 'Punto común derivado del estándar documentado'],
                ['orden' => 14, 'codigo_punto' => 'ALIM-14', 'grupo' => 'Alimentación', 'subgrupo' => 'Motor', 'nombre_punto' => 'Unión alimentación motor', 'posicion_tanque' => 'Común', 'tipo_punto' => 'unión', 'requiere_marchamo' => true, 'criterio_origen' => 'Punto común derivado del estándar documentado'],
                ['orden' => 15, 'codigo_punto' => 'ALIM-15', 'grupo' => 'Alimentación', 'subgrupo' => 'Motor', 'nombre_punto' => 'Entrada motor', 'posicion_tanque' => 'Común', 'tipo_punto' => 'motor', 'requiere_marchamo' => true, 'criterio_origen' => 'Punto común derivado del estándar documentado'],
                ['orden' => 16, 'codigo_punto' => 'RET-16', 'grupo' => 'Retorno', 'subgrupo' => 'Motor', 'nombre_punto' => 'Retorno motor', 'posicion_tanque' => 'Común', 'tipo_punto' => 'motor', 'requiere_marchamo' => true, 'criterio_origen' => 'Punto común derivado del estándar documentado'],
                ['orden' => 17, 'codigo_punto' => 'RET-17', 'grupo' => 'Retorno', 'subgrupo' => 'Motor', 'nombre_punto' => 'Unión retorno motor', 'posicion_tanque' => 'Común', 'tipo_punto' => 'unión', 'requiere_marchamo' => true, 'criterio_origen' => 'Punto común derivado del estándar documentado'],
                ['orden' => 18, 'codigo_punto' => 'RET-18', 'grupo' => 'Retorno', 'subgrupo' => 'Unión entre depósitos', 'nombre_punto' => 'Unión retorno izquierdo-derecho', 'posicion_tanque' => 'Izquierdo-Derecho', 'tipo_punto' => 'unión', 'requiere_marchamo' => true, 'criterio_origen' => 'Documentado como UNION RETORNO IZQ-DER'],
                ['orden' => 19, 'codigo_punto' => 'RET-19', 'grupo' => 'Retorno', 'subgrupo' => 'Depósito', 'nombre_punto' => 'Distribuidor retorno depósito izquierdo', 'posicion_tanque' => 'Izquierdo', 'tipo_punto' => 'distribuidor', 'requiere_marchamo' => true, 'criterio_origen' => 'Documentado en listado estándar'],
                ['orden' => 20, 'codigo_punto' => 'RET-20', 'grupo' => 'Retorno', 'subgrupo' => 'Depósito', 'nombre_punto' => 'Entrada retorno depósito izquierdo', 'posicion_tanque' => 'Izquierdo', 'tipo_punto' => 'retorno', 'requiere_marchamo' => true, 'criterio_origen' => 'Documentado en listado estándar'],
                ['orden' => 21, 'codigo_punto' => 'RET-21', 'grupo' => 'Retorno', 'subgrupo' => 'Depósito', 'nombre_punto' => 'Distribuidor retorno depósito derecho', 'posicion_tanque' => 'Derecho', 'tipo_punto' => 'distribuidor', 'requiere_marchamo' => true, 'criterio_origen' => 'Documentado en listado estándar'],
                ['orden' => 22, 'codigo_punto' => 'RET-22', 'grupo' => 'Retorno', 'subgrupo' => 'Depósito', 'nombre_punto' => 'Entrada retorno depósito derecho', 'posicion_tanque' => 'Derecho', 'tipo_punto' => 'retorno', 'requiere_marchamo' => true, 'criterio_origen' => 'Documentado en listado estándar'],
                ['orden' => 23, 'codigo_punto' => 'OTR-23', 'grupo' => 'Otros', 'subgrupo' => 'Depósito', 'nombre_punto' => 'Tapón depósito izquierdo', 'posicion_tanque' => 'Izquierdo', 'tipo_punto' => 'tapón', 'requiere_marchamo' => true, 'criterio_origen' => 'Documentado en listado estándar'],
                ['orden' => 24, 'codigo_punto' => 'OTR-24', 'grupo' => 'Otros', 'subgrupo' => 'Depósito', 'nombre_punto' => 'Respiradero depósito izquierdo', 'posicion_tanque' => 'Izquierdo', 'tipo_punto' => 'respiradero', 'requiere_marchamo' => true, 'criterio_origen' => 'Documentado en listado estándar'],
                ['orden' => 25, 'codigo_punto' => 'OTR-25', 'grupo' => 'Otros', 'subgrupo' => 'Depósito', 'nombre_punto' => 'Tapón depósito derecho', 'posicion_tanque' => 'Derecho', 'tipo_punto' => 'tapón', 'requiere_marchamo' => true, 'criterio_origen' => 'Documentado en listado estándar'],
                ['orden' => 26, 'codigo_punto' => 'OTR-26', 'grupo' => 'Otros', 'subgrupo' => 'Depósito', 'nombre_punto' => 'Respiradero depósito derecho', 'posicion_tanque' => 'Derecho', 'tipo_punto' => 'respiradero', 'requiere_marchamo' => true, 'criterio_origen' => 'Documentado en listado estándar'],
                ['orden' => 27, 'codigo_punto' => 'OTR-27', 'grupo' => 'Otros', 'subgrupo' => 'Depósito', 'nombre_punto' => 'Medidor depósito izquierdo/derecho', 'posicion_tanque' => 'Izquierdo-Derecho', 'tipo_punto' => 'medidor', 'requiere_marchamo' => true, 'criterio_origen' => 'Documentado como punto compartido'],
                ['orden' => 28, 'codigo_punto' => 'OTR-28', 'grupo' => 'Otros', 'subgrupo' => 'Depósito', 'nombre_punto' => 'Dreno depósito izquierdo', 'posicion_tanque' => 'Izquierdo', 'tipo_punto' => 'dreno', 'requiere_marchamo' => true, 'criterio_origen' => 'Documentado en listado estándar'],
                ['orden' => 29, 'codigo_punto' => 'OTR-29', 'grupo' => 'Otros', 'subgrupo' => 'Depósito', 'nombre_punto' => 'Dreno depósito derecho', 'posicion_tanque' => 'Derecho', 'tipo_punto' => 'dreno', 'requiere_marchamo' => true, 'criterio_origen' => 'Documentado en listado estándar'],
                ['orden' => 30, 'codigo_punto' => 'OTR-30', 'grupo' => 'Otros', 'subgrupo' => 'Filtro', 'nombre_punto' => 'Filtro combustible primario', 'posicion_tanque' => 'Común', 'tipo_punto' => 'filtro', 'requiere_marchamo' => true, 'criterio_origen' => 'Punto común derivado del estándar documentado'],
                ['orden' => 31, 'codigo_punto' => 'OTR-31', 'grupo' => 'Otros', 'subgrupo' => 'Filtro', 'nombre_punto' => 'Filtro combustible secundario', 'posicion_tanque' => 'Común', 'tipo_punto' => 'filtro', 'requiere_marchamo' => true, 'criterio_origen' => 'Punto común derivado del estándar documentado'],
                ['orden' => 32, 'codigo_punto' => 'OTR-32', 'grupo' => 'Otros', 'subgrupo' => 'Sensor', 'nombre_punto' => 'Sensor filtro combustible A', 'posicion_tanque' => 'Común', 'tipo_punto' => 'sensor', 'requiere_marchamo' => true, 'criterio_origen' => 'Punto común derivado del estándar documentado'],
                ['orden' => 33, 'codigo_punto' => 'OTR-33', 'grupo' => 'Otros', 'subgrupo' => 'Sensor', 'nombre_punto' => 'Sensor filtro combustible B', 'posicion_tanque' => 'Común', 'tipo_punto' => 'sensor', 'requiere_marchamo' => true, 'criterio_origen' => 'Punto común derivado del estándar documentado'],
                ['orden' => 34, 'codigo_punto' => 'OTR-34', 'grupo' => 'Otros', 'subgrupo' => 'Módulo', 'nombre_punto' => 'Base módulo entrada', 'posicion_tanque' => 'Común', 'tipo_punto' => 'módulo', 'requiere_marchamo' => true, 'criterio_origen' => 'Punto común derivado del estándar documentado'],
                ['orden' => 35, 'codigo_punto' => 'OTR-35', 'grupo' => 'Otros', 'subgrupo' => 'Módulo', 'nombre_punto' => 'Base módulo salida', 'posicion_tanque' => 'Común', 'tipo_punto' => 'módulo', 'requiere_marchamo' => true, 'criterio_origen' => 'Punto común derivado del estándar documentado'],
                ['orden' => 36, 'codigo_punto' => 'OTR-36', 'grupo' => 'Otros', 'subgrupo' => 'Transferencia', 'nombre_punto' => 'Desairador transferencia', 'posicion_tanque' => 'Común', 'tipo_punto' => 'transferencia', 'requiere_marchamo' => true, 'criterio_origen' => 'Punto común derivado del estándar documentado'],
                ['orden' => 37, 'codigo_punto' => 'OTR-37', 'grupo' => 'Otros', 'subgrupo' => 'Sensor', 'nombre_punto' => 'Sensor presión transferencia', 'posicion_tanque' => 'Común', 'tipo_punto' => 'sensor', 'requiere_marchamo' => true, 'criterio_origen' => 'Punto común derivado del estándar documentado'],
                ['orden' => 38, 'codigo_punto' => 'OTR-38', 'grupo' => 'Otros', 'subgrupo' => 'Transferencia', 'nombre_punto' => 'Tapón desairador transferencia', 'posicion_tanque' => 'Común', 'tipo_punto' => 'tapón', 'requiere_marchamo' => true, 'criterio_origen' => 'Punto común derivado del estándar documentado'],
        ];
    }

    private static function PLANTILLA_3_TANQUES(): array
    {
        return [
                ['orden' => 1, 'codigo_punto' => 'ALIM3-01', 'grupo' => 'Alimentación', 'subgrupo' => 'Depósito', 'nombre_punto' => 'Alimentación depósito izquierdo', 'posicion_tanque' => 'Izquierdo', 'tipo_punto' => 'depósito', 'requiere_marchamo' => true, 'criterio_origen' => 'Derivado desde estándar de 2 tanques'],
                ['orden' => 2, 'codigo_punto' => 'ALIM3-02', 'grupo' => 'Alimentación', 'subgrupo' => 'Depósito', 'nombre_punto' => 'Distribuidor alimentación depósito izquierdo', 'posicion_tanque' => 'Izquierdo', 'tipo_punto' => 'distribuidor', 'requiere_marchamo' => true, 'criterio_origen' => 'Derivado desde estándar de 2 tanques'],
                ['orden' => 3, 'codigo_punto' => 'ALIM3-03', 'grupo' => 'Alimentación', 'subgrupo' => 'Depósito', 'nombre_punto' => 'Alimentación depósito central', 'posicion_tanque' => 'Central', 'tipo_punto' => 'depósito', 'requiere_marchamo' => true, 'criterio_origen' => 'Derivado: tercer depósito'],
                ['orden' => 4, 'codigo_punto' => 'ALIM3-04', 'grupo' => 'Alimentación', 'subgrupo' => 'Depósito', 'nombre_punto' => 'Distribuidor alimentación depósito central', 'posicion_tanque' => 'Central', 'tipo_punto' => 'distribuidor', 'requiere_marchamo' => true, 'criterio_origen' => 'Derivado: tercer depósito'],
                ['orden' => 5, 'codigo_punto' => 'ALIM3-05', 'grupo' => 'Alimentación', 'subgrupo' => 'Depósito', 'nombre_punto' => 'Alimentación depósito derecho', 'posicion_tanque' => 'Derecho', 'tipo_punto' => 'depósito', 'requiere_marchamo' => true, 'criterio_origen' => 'Derivado desde estándar de 2 tanques'],
                ['orden' => 6, 'codigo_punto' => 'ALIM3-06', 'grupo' => 'Alimentación', 'subgrupo' => 'Depósito', 'nombre_punto' => 'Distribuidor alimentación depósito derecho', 'posicion_tanque' => 'Derecho', 'tipo_punto' => 'distribuidor', 'requiere_marchamo' => true, 'criterio_origen' => 'Derivado desde estándar de 2 tanques'],
                ['orden' => 7, 'codigo_punto' => 'ALIM3-07', 'grupo' => 'Alimentación', 'subgrupo' => 'Unión entre depósitos', 'nombre_punto' => 'Unión alimentación izquierdo-central', 'posicion_tanque' => 'Izquierdo-Central', 'tipo_punto' => 'unión', 'requiere_marchamo' => true, 'criterio_origen' => 'Derivado: reemplaza unión izq-der'],
                ['orden' => 8, 'codigo_punto' => 'ALIM3-08', 'grupo' => 'Alimentación', 'subgrupo' => 'Unión entre depósitos', 'nombre_punto' => 'Unión alimentación central-derecho', 'posicion_tanque' => 'Central-Derecho', 'tipo_punto' => 'unión', 'requiere_marchamo' => true, 'criterio_origen' => 'Derivado: reemplaza unión izq-der'],
                ['orden' => 9, 'codigo_punto' => 'ALIM-06', 'grupo' => 'Alimentación', 'subgrupo' => 'Filtro primario', 'nombre_punto' => 'Entrada filtro combustible primario', 'posicion_tanque' => 'Común', 'tipo_punto' => 'línea', 'requiere_marchamo' => true, 'criterio_origen' => 'Punto común derivado del estándar documentado'],
                ['orden' => 10, 'codigo_punto' => 'ALIM-07', 'grupo' => 'Alimentación', 'subgrupo' => 'Filtro primario', 'nombre_punto' => 'Dreno filtro combustible primario', 'posicion_tanque' => 'Común', 'tipo_punto' => 'filtro', 'requiere_marchamo' => true, 'criterio_origen' => 'Punto común derivado del estándar documentado'],
                ['orden' => 11, 'codigo_punto' => 'ALIM-08', 'grupo' => 'Alimentación', 'subgrupo' => 'Filtro primario', 'nombre_punto' => 'Salida filtro combustible primario', 'posicion_tanque' => 'Común', 'tipo_punto' => 'línea', 'requiere_marchamo' => true, 'criterio_origen' => 'Corrección ortográfica sugerida: Filtro'],
                ['orden' => 12, 'codigo_punto' => 'ALIM-09', 'grupo' => 'Alimentación', 'subgrupo' => 'Filtro secundario', 'nombre_punto' => 'Alimentador filtro combustible secundario', 'posicion_tanque' => 'Común', 'tipo_punto' => 'línea', 'requiere_marchamo' => true, 'criterio_origen' => 'Punto común derivado del estándar documentado'],
                ['orden' => 13, 'codigo_punto' => 'ALIM-10', 'grupo' => 'Alimentación', 'subgrupo' => 'Filtro secundario', 'nombre_punto' => 'Entrada filtro combustible secundario', 'posicion_tanque' => 'Común', 'tipo_punto' => 'línea', 'requiere_marchamo' => true, 'criterio_origen' => 'Punto común derivado del estándar documentado'],
                ['orden' => 14, 'codigo_punto' => 'ALIM-11', 'grupo' => 'Alimentación', 'subgrupo' => 'Filtro secundario', 'nombre_punto' => 'Salida filtro combustible secundario', 'posicion_tanque' => 'Común', 'tipo_punto' => 'línea', 'requiere_marchamo' => true, 'criterio_origen' => 'Corrección ortográfica sugerida: Filtro'],
                ['orden' => 15, 'codigo_punto' => 'ALIM-12', 'grupo' => 'Alimentación', 'subgrupo' => 'Transferencia', 'nombre_punto' => 'Entrada transferencia', 'posicion_tanque' => 'Común', 'tipo_punto' => 'transferencia', 'requiere_marchamo' => true, 'criterio_origen' => 'Punto común derivado del estándar documentado'],
                ['orden' => 16, 'codigo_punto' => 'ALIM-13', 'grupo' => 'Alimentación', 'subgrupo' => 'Transferencia', 'nombre_punto' => 'Salida transferencia', 'posicion_tanque' => 'Común', 'tipo_punto' => 'transferencia', 'requiere_marchamo' => true, 'criterio_origen' => 'Punto común derivado del estándar documentado'],
                ['orden' => 17, 'codigo_punto' => 'ALIM-14', 'grupo' => 'Alimentación', 'subgrupo' => 'Motor', 'nombre_punto' => 'Unión alimentación motor', 'posicion_tanque' => 'Común', 'tipo_punto' => 'unión', 'requiere_marchamo' => true, 'criterio_origen' => 'Punto común derivado del estándar documentado'],
                ['orden' => 18, 'codigo_punto' => 'ALIM-15', 'grupo' => 'Alimentación', 'subgrupo' => 'Motor', 'nombre_punto' => 'Entrada motor', 'posicion_tanque' => 'Común', 'tipo_punto' => 'motor', 'requiere_marchamo' => true, 'criterio_origen' => 'Punto común derivado del estándar documentado'],
                ['orden' => 19, 'codigo_punto' => 'RET-16', 'grupo' => 'Retorno', 'subgrupo' => 'Motor', 'nombre_punto' => 'Retorno motor', 'posicion_tanque' => 'Común', 'tipo_punto' => 'motor', 'requiere_marchamo' => true, 'criterio_origen' => 'Punto común derivado del estándar documentado'],
                ['orden' => 20, 'codigo_punto' => 'RET-17', 'grupo' => 'Retorno', 'subgrupo' => 'Motor', 'nombre_punto' => 'Unión retorno motor', 'posicion_tanque' => 'Común', 'tipo_punto' => 'unión', 'requiere_marchamo' => true, 'criterio_origen' => 'Punto común derivado del estándar documentado'],
                ['orden' => 21, 'codigo_punto' => 'RET-18', 'grupo' => 'Retorno', 'subgrupo' => 'Unión entre depósitos', 'nombre_punto' => 'Unión retorno izquierdo-central', 'posicion_tanque' => 'Izquierdo-Central', 'tipo_punto' => 'unión', 'requiere_marchamo' => true, 'criterio_origen' => 'Derivado: reemplaza unión izq-der'],
                ['orden' => 22, 'codigo_punto' => 'RET-19', 'grupo' => 'Retorno', 'subgrupo' => 'Unión entre depósitos', 'nombre_punto' => 'Unión retorno central-derecho', 'posicion_tanque' => 'Central-Derecho', 'tipo_punto' => 'unión', 'requiere_marchamo' => true, 'criterio_origen' => 'Derivado: reemplaza unión izq-der'],
                ['orden' => 23, 'codigo_punto' => 'RET-20', 'grupo' => 'Retorno', 'subgrupo' => 'Depósito', 'nombre_punto' => 'Distribuidor retorno depósito izquierdo', 'posicion_tanque' => 'Izquierdo', 'tipo_punto' => 'distribuidor', 'requiere_marchamo' => true, 'criterio_origen' => 'Derivado desde estándar de 2 tanques'],
                ['orden' => 24, 'codigo_punto' => 'RET-21', 'grupo' => 'Retorno', 'subgrupo' => 'Depósito', 'nombre_punto' => 'Entrada retorno depósito izquierdo', 'posicion_tanque' => 'Izquierdo', 'tipo_punto' => 'retorno', 'requiere_marchamo' => true, 'criterio_origen' => 'Derivado desde estándar de 2 tanques'],
                ['orden' => 25, 'codigo_punto' => 'RET-22', 'grupo' => 'Retorno', 'subgrupo' => 'Depósito', 'nombre_punto' => 'Distribuidor retorno depósito central', 'posicion_tanque' => 'Central', 'tipo_punto' => 'distribuidor', 'requiere_marchamo' => true, 'criterio_origen' => 'Derivado: tercer depósito'],
                ['orden' => 26, 'codigo_punto' => 'RET-23', 'grupo' => 'Retorno', 'subgrupo' => 'Depósito', 'nombre_punto' => 'Entrada retorno depósito central', 'posicion_tanque' => 'Central', 'tipo_punto' => 'retorno', 'requiere_marchamo' => true, 'criterio_origen' => 'Derivado: tercer depósito'],
                ['orden' => 27, 'codigo_punto' => 'RET-24', 'grupo' => 'Retorno', 'subgrupo' => 'Depósito', 'nombre_punto' => 'Distribuidor retorno depósito derecho', 'posicion_tanque' => 'Derecho', 'tipo_punto' => 'distribuidor', 'requiere_marchamo' => true, 'criterio_origen' => 'Derivado desde estándar de 2 tanques'],
                ['orden' => 28, 'codigo_punto' => 'RET-25', 'grupo' => 'Retorno', 'subgrupo' => 'Depósito', 'nombre_punto' => 'Entrada retorno depósito derecho', 'posicion_tanque' => 'Derecho', 'tipo_punto' => 'retorno', 'requiere_marchamo' => true, 'criterio_origen' => 'Derivado desde estándar de 2 tanques'],
                ['orden' => 29, 'codigo_punto' => 'OTR3-26', 'grupo' => 'Otros', 'subgrupo' => 'Depósito', 'nombre_punto' => 'Tapón depósito izquierdo', 'posicion_tanque' => 'Izquierdo', 'tipo_punto' => 'tapón', 'requiere_marchamo' => true, 'criterio_origen' => 'Derivado desde estándar de 2 tanques'],
                ['orden' => 30, 'codigo_punto' => 'OTR3-27', 'grupo' => 'Otros', 'subgrupo' => 'Depósito', 'nombre_punto' => 'Respiradero depósito izquierdo', 'posicion_tanque' => 'Izquierdo', 'tipo_punto' => 'respiradero', 'requiere_marchamo' => true, 'criterio_origen' => 'Derivado desde estándar de 2 tanques'],
                ['orden' => 31, 'codigo_punto' => 'OTR3-28', 'grupo' => 'Otros', 'subgrupo' => 'Depósito', 'nombre_punto' => 'Tapón depósito central', 'posicion_tanque' => 'Central', 'tipo_punto' => 'tapón', 'requiere_marchamo' => true, 'criterio_origen' => 'Derivado: tercer depósito'],
                ['orden' => 32, 'codigo_punto' => 'OTR3-29', 'grupo' => 'Otros', 'subgrupo' => 'Depósito', 'nombre_punto' => 'Respiradero depósito central', 'posicion_tanque' => 'Central', 'tipo_punto' => 'respiradero', 'requiere_marchamo' => true, 'criterio_origen' => 'Derivado: tercer depósito'],
                ['orden' => 33, 'codigo_punto' => 'OTR3-30', 'grupo' => 'Otros', 'subgrupo' => 'Depósito', 'nombre_punto' => 'Tapón depósito derecho', 'posicion_tanque' => 'Derecho', 'tipo_punto' => 'tapón', 'requiere_marchamo' => true, 'criterio_origen' => 'Derivado desde estándar de 2 tanques'],
                ['orden' => 34, 'codigo_punto' => 'OTR3-31', 'grupo' => 'Otros', 'subgrupo' => 'Depósito', 'nombre_punto' => 'Respiradero depósito derecho', 'posicion_tanque' => 'Derecho', 'tipo_punto' => 'respiradero', 'requiere_marchamo' => true, 'criterio_origen' => 'Derivado desde estándar de 2 tanques'],
                ['orden' => 35, 'codigo_punto' => 'OTR3-32', 'grupo' => 'Otros', 'subgrupo' => 'Depósito', 'nombre_punto' => 'Medidor depósito izquierdo', 'posicion_tanque' => 'Izquierdo', 'tipo_punto' => 'medidor', 'requiere_marchamo' => true, 'criterio_origen' => 'Derivado: separar medidor por depósito para 3 tanques'],
                ['orden' => 36, 'codigo_punto' => 'OTR3-33', 'grupo' => 'Otros', 'subgrupo' => 'Depósito', 'nombre_punto' => 'Medidor depósito central', 'posicion_tanque' => 'Central', 'tipo_punto' => 'medidor', 'requiere_marchamo' => true, 'criterio_origen' => 'Derivado: tercer depósito'],
                ['orden' => 37, 'codigo_punto' => 'OTR3-34', 'grupo' => 'Otros', 'subgrupo' => 'Depósito', 'nombre_punto' => 'Medidor depósito derecho', 'posicion_tanque' => 'Derecho', 'tipo_punto' => 'medidor', 'requiere_marchamo' => true, 'criterio_origen' => 'Derivado: separar medidor por depósito para 3 tanques'],
                ['orden' => 38, 'codigo_punto' => 'OTR3-35', 'grupo' => 'Otros', 'subgrupo' => 'Depósito', 'nombre_punto' => 'Dreno depósito izquierdo', 'posicion_tanque' => 'Izquierdo', 'tipo_punto' => 'dreno', 'requiere_marchamo' => true, 'criterio_origen' => 'Derivado desde estándar de 2 tanques'],
                ['orden' => 39, 'codigo_punto' => 'OTR3-36', 'grupo' => 'Otros', 'subgrupo' => 'Depósito', 'nombre_punto' => 'Dreno depósito central', 'posicion_tanque' => 'Central', 'tipo_punto' => 'dreno', 'requiere_marchamo' => true, 'criterio_origen' => 'Derivado: tercer depósito'],
                ['orden' => 40, 'codigo_punto' => 'OTR3-37', 'grupo' => 'Otros', 'subgrupo' => 'Depósito', 'nombre_punto' => 'Dreno depósito derecho', 'posicion_tanque' => 'Derecho', 'tipo_punto' => 'dreno', 'requiere_marchamo' => true, 'criterio_origen' => 'Derivado desde estándar de 2 tanques'],
                ['orden' => 41, 'codigo_punto' => 'OTR-30', 'grupo' => 'Otros', 'subgrupo' => 'Filtro', 'nombre_punto' => 'Filtro combustible primario', 'posicion_tanque' => 'Común', 'tipo_punto' => 'filtro', 'requiere_marchamo' => true, 'criterio_origen' => 'Punto común derivado del estándar documentado'],
                ['orden' => 42, 'codigo_punto' => 'OTR-31', 'grupo' => 'Otros', 'subgrupo' => 'Filtro', 'nombre_punto' => 'Filtro combustible secundario', 'posicion_tanque' => 'Común', 'tipo_punto' => 'filtro', 'requiere_marchamo' => true, 'criterio_origen' => 'Punto común derivado del estándar documentado'],
                ['orden' => 43, 'codigo_punto' => 'OTR-32', 'grupo' => 'Otros', 'subgrupo' => 'Sensor', 'nombre_punto' => 'Sensor filtro combustible A', 'posicion_tanque' => 'Común', 'tipo_punto' => 'sensor', 'requiere_marchamo' => true, 'criterio_origen' => 'Punto común derivado del estándar documentado'],
                ['orden' => 44, 'codigo_punto' => 'OTR-33', 'grupo' => 'Otros', 'subgrupo' => 'Sensor', 'nombre_punto' => 'Sensor filtro combustible B', 'posicion_tanque' => 'Común', 'tipo_punto' => 'sensor', 'requiere_marchamo' => true, 'criterio_origen' => 'Punto común derivado del estándar documentado'],
                ['orden' => 45, 'codigo_punto' => 'OTR-34', 'grupo' => 'Otros', 'subgrupo' => 'Módulo', 'nombre_punto' => 'Base módulo entrada', 'posicion_tanque' => 'Común', 'tipo_punto' => 'módulo', 'requiere_marchamo' => true, 'criterio_origen' => 'Punto común derivado del estándar documentado'],
                ['orden' => 46, 'codigo_punto' => 'OTR-35', 'grupo' => 'Otros', 'subgrupo' => 'Módulo', 'nombre_punto' => 'Base módulo salida', 'posicion_tanque' => 'Común', 'tipo_punto' => 'módulo', 'requiere_marchamo' => true, 'criterio_origen' => 'Punto común derivado del estándar documentado'],
                ['orden' => 47, 'codigo_punto' => 'OTR-36', 'grupo' => 'Otros', 'subgrupo' => 'Transferencia', 'nombre_punto' => 'Desairador transferencia', 'posicion_tanque' => 'Común', 'tipo_punto' => 'transferencia', 'requiere_marchamo' => true, 'criterio_origen' => 'Punto común derivado del estándar documentado'],
                ['orden' => 48, 'codigo_punto' => 'OTR-37', 'grupo' => 'Otros', 'subgrupo' => 'Sensor', 'nombre_punto' => 'Sensor presión transferencia', 'posicion_tanque' => 'Común', 'tipo_punto' => 'sensor', 'requiere_marchamo' => true, 'criterio_origen' => 'Punto común derivado del estándar documentado'],
                ['orden' => 49, 'codigo_punto' => 'OTR-38', 'grupo' => 'Otros', 'subgrupo' => 'Transferencia', 'nombre_punto' => 'Tapón desairador transferencia', 'posicion_tanque' => 'Común', 'tipo_punto' => 'tapón', 'requiere_marchamo' => true, 'criterio_origen' => 'Punto común derivado del estándar documentado'],
        ];
    }

}
